package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cuckoo",
    hdrs = ["cuckoo.hpp"],
)

cc_library(
    name = "fastio",
    srcs = ["fastio.cpp"],
    hdrs = ["fastio.hpp"],
)
