package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "text_ui",
    srcs = ["text_ui.cpp"],
    deps = [
        "//enumerable:clique",
        "//enumerator:sequential",
        "//external:gflags",
        "//util:graph",
        "@com_google_absl//absl/memory",
    ],
)
